pipelines:
    -
        name: check
        description: Newly uploaded patchsets enter this pipeline to get an initial +1/-1 from Jenkins
        success-message: Build succeeded (check pipeline).
        failure-message: Build failed (check pipeline). Please check the logs referenced below. For more information on how to proceed, please see https://wiki.asterisk.org/wiki/display/AST/Continuous+Integration
        manager: IndependentPipelineManager
        source: gerrit
        precedence: normal
        require:
            open: True
            current-patchset: True
        trigger:
            gerrit:
                - event: patchset-created
                - event: change-restored
                - event: draft-published
                - event: comment-added
                  comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
        success:
            gerrit:
                verified: 1
        failure:
            gerrit:
                verified: 0
    -
        name: gate
        description: Changes that have been approved by mergers are enqueued in this pipeline.
        success-message: Build succeeded (gate pipeline).
        failure-message: Build failed (gate pipeline). Please check the logs referenced below. For more information on how to proceed, please see https://wiki.asterisk.org/wiki/display/AST/Continuous+Integration
        manager: DependentPipelineManager
        source: gerrit
        precedence: high
        require:
            open: True
            current-patchset: True
            approval:
                -
                    verified: [1, 2]
        trigger:
            gerrit:
                - event: comment-added
                  approval:
                    - code-review: 2
                - event: comment-added
                  comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(regate)
        success:
            gerrit:
                verified: 2
                submit: true
        failure:
            gerrit:
                verified: 0
        window-floor: 20
        window-increase-factor: 2
    -
        name: post
        description: This pipeline runs jobs that operate after each change is merged.
        manager: IndependentPipelineManager
        source: gerrit
        trigger:
            gerrit:
                -
                    event: ref-updated
                    ref: ^(?!refs/).*$
    -
        name: tag
        description: This pipeline runs jobs in response to any tag event.
        manager: IndependentPipelineManager
        source: gerrit
        trigger:
            gerrit:
                -
                    event: ref-updated
                    ref: ^refs/tags/.*$
    -
        name: periodic-stable
        description: Periodic checks of the stable branches.
        manager: IndependentPipelineManager
        source: gerrit
        precedence: low
        trigger:
            timer:
                - time: '0 0 * * *'
        failure:
            smtp:
                from: asteriskteam@digium.com
                to: test-results@lists.digium.com
                subject: 'Stable check of {change.project} failed'
    -
        name: periodic-realtime
        description: Periodic checks of the realtime capable test branches.
        manager: IndependentPipelineManager
        source: gerrit
        precedence: low
        trigger:
            timer:
                - time: '0 0 * * *'
        failure:
            smtp:
                from: asteriskteam@digium.com
                to: test-results@lists.digium.com
                subject: 'Realtime test check of {change.project} failed'
    -
        name: periodic-documentation
        description: Nightly wiki documentation update of release branches.
        manager: IndependentPipelineManager
        source: gerrit
        precedence: low
        trigger:
            timer:
                - time: '0 0 * * *'
        failure:
            smtp:
                from: asteriskteam@digium.com
                to: test-results@lists.digium.com
                subject: 'Wiki documentation update of {change.project} failed'
    -
        name: periodic-ref_debug
        description: Weekly check of the stable branches with REF_DEBUG.
        manager: IndependentPipelineManager
        source: gerrit
        precedence: low
        trigger:
            timer:
                - time: '0 0 * * 6'
        failure:
            smtp:
                from: asteriskteam@digium.com
                to: test-results@lists.digium.com
                subject: 'Weekly REF_DEBUG test check of {change.project} failed'
    -
        name: merge-check
        description: >
          Each time a change merges, this pipeline verifies that all open changes
          on the same project are still mergeable.
        failure-message: Build failed (merge-check pipeline).
        manager: IndependentPipelineManager
        ignore-dependencies: true
        source: gerrit
        precedence: low
        require:
            approval:
                -       
                    verified: [1, 2]
        trigger:
            zuul:
                - event: project-change-merged
        merge-failure:
            gerrit:
                verified: -1

jobs:
    - name: 'gate-asterisk-ari'
      branch: '(12|13|master)'
    - name: 'gate-asterisk-external-mwi'
      branch: '(12|13|master)'

project-templates:
    -
        name: merge-check
        merge-check:
            - noop
    -
        name: python-jobs
        check:
            - 'check-{name}-pep8'
    -
        name: testsuite-jobs
        check:
            - 'check-testsuite'
        gate:
            - 'gate-testsuite'
    -
        name: asterisk-jobs
        check:
            - 'check-asterisk'
            - 'check-asterisk-32'
            - 'check-asterisk-64'
        gate:
            - 'gate-asterisk'
            - 'gate-asterisk-channel-drivers'
            - 'gate-asterisk-external-mwi'
            - 'gate-asterisk-ari'
    -
        name: periodic-asterisk
        periodic-stable:
            - 'periodic-{name}-{branch}'
        periodic-ref_debug:
            - 'periodic-ref_debug-{name}-{branch}'
    -
        name: periodic-realtime-asterisk
        periodic-realtime:
            - 'periodic-realtime-{name}-{branch}'
    -
        name: periodic-documentation-asterisk
        periodic-documentation:
            - 'periodic-documentation-{name}-{branch}'

projects:
    -
        name: 'testsuite'
        template:
            - name: 'merge-check'
            - name: 'python-jobs'
            - name: 'testsuite-jobs'
    -
        name: 'asterisk'
        template:
            - name: 'merge-check'
            - name: 'asterisk-jobs'
            - name: 'periodic-asterisk'
              branch: '11'
            - name: 'periodic-asterisk'
              branch: '13'
            - name: 'periodic-asterisk'
              branch: 'master'
            - name: 'periodic-realtime-asterisk'
              branch: '13'
            - name: 'periodic-realtime-asterisk'
              branch: 'master'
            - name: 'periodic-documentation-asterisk'
              branch: '11'
            - name: 'periodic-documentation-asterisk'
              branch: '13'

